### ISSUE TITLE
make deploy takes quite some time to complete.

### ISSUE THREAD

**Issue by rajat-soda** [ran-isenberg/aws-lambda-handler-cookbook#827] opened 2024-04-19 10:54 UTC
**Describe the bug**
Time taken for 'make deploy' is very long. 
Please try to remove the unwanted steps in the 'make' command to improve performance. 

Also , Please state the prereqs clearly , as to what permissions are required before executing 'make deploy'. 

I got the error This CDK deployment requires bootstrap stack version '6', but during the confirmation via SSM parameter /cdk-bootstrap/hnb659fds/version the following error occurred: AccessDeniedException: User: arn:aws:iam::262xxx2701:user/xxxx@yyy.com is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:ap-south-1:26xxxx822701:parameter/cdk-bootstrap/hnb659fds/version because no identity-based policy allows the ssm:GetParameter action

**To Reproduce**
execute 'make deploy'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. mac]
 - OS: [mac 14.1]

**Additional context**

**Comment by ran-isenberg** [comment] 2024-04-19 10:59
Hi,
It seems you have might several issues:
1. You didnt install the correct CDK version in the template.
2. Most likley - you didnt run CDK bootstrap on your AWS account or it was a very old version. That's a pre requirement to work with CDK on any account, not related to the cookbook. https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html

As for the deploy time, that's pure CDK/Cloudformation process, nothing i can do about that, first deploy is always the longest.

**Comment by ran-isenberg** [comment] 2024-04-19 11:00
I'll update the cdk bootstrp into the readme. 
Closing as not a bug

**Closed by ran-isenberg** 2024-04-19 11:00 UTC

**Comment by ran-isenberg** [comment] 2024-04-19 11:09
@rajat-soda make sure your role has permissions to access the cdk boostrap resources such as SSM get parameter etc. Your issue is not related to this project. This project doesnt contain SSM resources.

**Comment by ran-isenberg** [comment] 2024-04-19 11:24
> Thanks for the quick and pointed response. I am new to using CDK , Please post links to getting started with CDK and what all IAM permission (for this sample app) are needed to get started with CDK

it's in the link i sent above. Please follow official CDK docs. You can see the resources CDK requires under "Bootstrapping template differences - resources".

**Comment by rajat-soda** [comment] 2024-04-22 08:11
I would like to integrate the Async eventing piece to the existing [aws-lambda-handler-cookbook](https://github.com/ran-isenberg/aws-lambda-handler-cookbook) , the one that  Hietor Lessa was talking about in the presentation . Any pointers to that code base will be helpful.

**Comment by ran-isenberg** [comment] 2024-04-22 08:28
@rajat-soda  you can all the code from our talk here: https://github.com/ran-isenberg/serverless-python-demo

**Comment by rajat-soda** [comment] 2024-04-24 04:29
For accessing the APIs of the. "serverless-python-demo" is there any documentation OR README. 
I am hitting a 401 - "message": "Unauthorized" , looks like I must be missing the user/passwd for accessing this API

**Comment by ran-isenberg** [comment] 2024-04-25 06:42
The repo has readme and github pages. The apis are protected by cognito. It's all in the docs

**Comment by rajat-soda** [comment] 2024-04-29 16:47
Thanks for the pointers, however  I could not find sufficient documentation regarding using /configuring the Cognito User .  Do I need to generate the token using CLI / UI and use it in  a API client like Postman .  Please elaborate.

**Comment by ran-isenberg** [comment] 2024-04-29 19:37
Hi, it creates a user pool and the tests use a predefined user , login and send the token. 
From here, you can do whatever you want. Refer to the cognito documentation or do it manually in the console. It's up to you. Can't help more than that.

**Comment by rajat-soda** [comment] 2024-04-30 00:45
Can the APIs of [serverless-python-demo] project be invoked just after deploying the project to AWS, with the "test" user .
OR is a new user , usergroup , roles required to be setup and attached to the APIs .
